spring:
  application:
    name: desafioItau

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/db_desafio_itau
    username: springuser
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY:XXX}
        secret-key: ${AWS_SECRET_KEY:XXXX}
      region:
        static: ${AWS_REGION:us-east-2}
      sns:
        topic:
          book-topic:
            arn: ${AWS_ARN:arn:aws:sns:us-east-2:307946635270:book-topic}

server:
  port: 8081

# JPA RDS Configuration
# Uncomment and configure these lines if using AWS RDS
# spring:
#   datasource:
#     url: # put your AWS RDS URL here
#     driverClassName: com.mysql.cj.jdbc.Driver
#     username: ${dbUser}
#     password: ${dbPass}