services:
  mysqql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=db_desafio_itau
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"