server:
  port: 8080

spring:
  application:
    name: desafioItau

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # http://localhost:8080/h2-console
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${DATABASE_USERNAME:sa}

    password: ${DATABASE_PASSWORD:password}
    driver-class-name: ${com.mysql.cj.jdbc.Driver:org.h2.Driver}

  cloud:
    aws:
      credentials:
        access-key: ${ACCESS_KEY_AWS}
        secret-key: ${SECRET_KEY_AWS}
      region:
        static: ${REGION_AWS:us-east-2}

      sns:
        topic:
          book-topic:
            arn: ${ARN_AWS}


