spring:
  application:
    name: desafioItau

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  jdbc:mysql://localhost:3306/db_desafio_itau
  datasource:
    url: ${{DATABASE_URL}}
    username: ${{DATABASE_USERNAME}}
    password: ${{DATABASE_PASSWORD}}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    aws:
      credentials:
        access-key: ${ACCESS_KEY_AWS}
        secret-key: ${SECRET_KEY_AWS}
      region:
        static: ${REGION_AWS}
      sns:
        topic:
          book-topic:
            arn: ${ARN_AWS}

server:
  port: 8080

# JPA RDS Configuration
# Uncomment and configure these lines if using AWS RDS
# spring:
#   datasource:
#     url: # put your AWS RDS URL here
#     driverClassName: com.mysql.cj.jdbc.Driver
#     username: ${dbUser}
#     password: ${dbPass}