name: Deploy Application BookItau

on:
  push:
    branches: [developer]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t ricardocanuto/elisioricardo .

      - name: Push image docker
        run: docker push ricardocanuto/elisioricardo
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
  
      - name: Build and run containers
        run: |
          docker-compose up -d
          docker-compose ps

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker Hub
        run: docker pull ricardocanuto/elisioricardo:latest
      - name: Remove docker container
        run: docker rm -f desafioItau
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name desafioItau ricardocanuto/elisioricardo