name: Deploy Application BookItau

on:
  push:
    branches: [developer]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login Docker Hub
        env:
          DOCKER_USERNAME: 'elisircsilva@hotmail.com'
          DOCKER_PASSWORD: '@#Vitoria2'
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - name: Build docker image
        run: docker build -t elisiorcsilva/desafioItau .
      - name: Push image docker
        run: docker push elisiorcsilva/desafioItau

