name: Deploy Application BookItau

on:
  push:
    branches: [developer]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t ricardocanuto/elisioricardo .
      - name: Push image docker
        run: docker push ricardocanuto/elisioricardo

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker Hub
        run: docker pull ricardocanuto/elisioricardo:latest
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name desafioItau ricardocanuto/elisioricardo