name: Deploy Application BookAWS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t ricardocanuto/elisioricardo .

      - name: Push image docker
        run: docker push ricardocanuto/elisioricardo

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull image from docker Hub
        run: docker pull ricardocanuto/elisioricardo:latest

      - name: Remove docker container
        run: docker rm -f desafioAWS

      - name: Run docker container
        run: docker run -d -p 8080:8080 -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} -e DATABASE_PASSWORD='${{ secrets.DATABASE_PASSWORD }}' -e DATABASE_URL='${{ secrets.DATABASE_URL }}'  -e ARN_AWS='${{secrets.ARN_AWS}}' -e ACCESS_KEY_AWS='${{ secrets.ACCESS_KEY_AWS }}' -e SECRET_KEY_AWS='${{ secrets.SECRET_KEY_AWS }}' -e REGION_AWS='${{ secrets.REGION_AWS }}' --name desafioItau ricardocanuto/elisioricardo